apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: web-app
  namespace: web-app
spec:
  chart:
    spec:
      chart: ./web-app-helm-chart
      sourceRef:
        kind: GitRepository
        name: web-app-gitrepository
        namespace: flux-system
  interval: 5m
  values:
    # You can override values.yaml here if needed